# Generated by Django 4.1.5 on 2023-01-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_products_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_code',
            field=models.CharField(max_length=55, unique=True),
        ),
    ]
