# Generated by Django 4.1.5 on 2023-04-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_unit_in_stock_products_quantity_in_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
