# Generated by Django 4.2 on 2023-04-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_sales_stock_left"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="unit_id",
            field=models.CharField(
                choices=[("pcs", "PCS"), ("dozen", "DOZEN")],
                help_text="For example pcs or dozen",
                max_length=255,
            ),
        ),
    ]
