# Generated by Django 4.2 on 2023-04-20 14:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_alter_products_unit_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="unit_id",
            new_name="unit_of_measure",
        ),
    ]
