# Generated by Django 4.2 on 2023-04-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_rename_unit_id_products_unit_of_measure"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="product_image",
            field=models.ImageField(
                default="images/default.png", null=True, upload_to="images/products/"
            ),
        ),
    ]
