# Generated by Django 4.2 on 2023-04-23 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0009_products_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="sales",
            name="date_sold",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
