# Generated by Django 4.2 on 2023-04-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0010_sales_date_sold"),
    ]

    operations = [
        migrations.AddField(
            model_name="sales",
            name="current_cost_price",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
