# Generated by Django 4.2 on 2023-05-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0012_supplier_purchases"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="new_arrival",
            field=models.BooleanField(default=False),
        ),
    ]
