# Generated by Django 4.2 on 2023-05-03 06:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0013_products_new_arrival"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchases",
            old_name="date",
            new_name="purchase_date",
        ),
        migrations.RenameField(
            model_name="purchases",
            old_name="cost_price",
            new_name="purchase_price",
        ),
    ]
