# Generated by Django 4.2 on 2023-05-03 06:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0014_rename_date_purchases_purchase_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchases",
            old_name="Supplier",
            new_name="supplier",
        ),
    ]
