# Generated by Django 4.1.10 on 2023-09-14 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0017_products_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchases",
            name="purchase_date",
            field=models.DateField(default=datetime.date(2023, 9, 11)),
        ),
    ]
