# Generated by Django 4.1.10 on 2023-10-02 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0025_alter_products_category_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="product_name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="sales",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="product.products"
            ),
        ),
    ]
