# Generated by Django 4.0.3 on 2022-03-07 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_catergory_id_products_catergory_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('-publish',)},
        ),
        migrations.AddField(
            model_name='products',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterModelTable(
            name='products',
            table='Products',
        ),
    ]
