# Generated by Django 4.0.3 on 2022-04-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_catergory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='catergory_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
