# Generated by Django 4.0.3 on 2022-04-10 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_catergory_id_category_category_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
    ]
