# Generated by Django 4.0.3 on 2022-04-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_category_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
