# Generated by Django 4.0.3 on 2022-04-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_category_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_id',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='images/default.png', null=True, upload_to='images/'),
        ),
    ]
