# Generated by Django 4.0.3 on 2022-04-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_category_category_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='products',
            name='unit_id',
            field=models.CharField(choices=[('pcs', 'PCS'), ('dozen', 'DOZEN')], max_length=255),
        ),
    ]
